In [1]:
import tensorflow as tf

# TensorFlow Data Type
 - Constant
 - Placeholder
 - Variables

# tf.constant: 상수

In [2]:
a = tf.constant(10)
b = tf.constant(20)
c = tf.add(a, b)

# Tensor의 기본 메타 정보만 보여줌
print(c)

Tensor("Add:0", shape=(), dtype=int32)


![](data/add.png)

In [3]:
# 그래프를 실행할 세션을 구성
sess = tf.Session()

# sess.run: 설정한 텐서 그래프 실행

print(sess.run([a, b, c]))

[10, 20, 30]


# tf.placeholder: 입력값을 받는 플레이스홀더

In [4]:
X = tf.placeholder(tf.float32, [None, 2])
print(X)

Tensor("Placeholder:0", shape=(?, 2), dtype=float32)


In [5]:
# X 플레이스홀더에 대입하는 값
x_data = [[1, 2], [3, 4]]

In [6]:
# X값 print 하기
print(sess.run(X, feed_dict={X: x_data}))

[[ 1.  2.]
 [ 3.  4.]]


# tf.Variable: 그래프를 계산하면서 최적화 할 변수들

In [7]:
# tf.random_normal: 정규분포(평균 = 0, 표준편차 =1)
W = tf.Variable([[1., 1.],[2., 2.]]) #초깃값을 고정해서 배정
b = tf.Variable(tf.random_normal([2, 2]))#초깃값을 정규분포에서 추출

# 입력값과 변수들을 계산할 수식을 작성.
H = tf.matmul(X, W) + b

In [8]:
sess = tf.Session()

# Variable은 초기화를 해야함
sess.run(tf.global_variables_initializer())

print(sess.run(W))
print(sess.run(b))


print(sess.run(H, feed_dict={X: x_data}))

[[ 1.  1.]
 [ 2.  2.]]
[[-1.04324007 -0.72200531]
 [-0.38210982 -0.8329109 ]]
[[  3.95675993   4.27799463]
 [ 10.61789036  10.16708946]]
