In [1]:
# load tensorflow library
import tensorflow as tf

# TensorFlow Data Type
 - Constant: 상수
     - `tf.constant`
 - Placeholder: 입력값을 받는 Placeholder
     - `tf.placeholder`
 - Variable: 최적화 할 변수들
     - `tf.Variable`

# tf.constant

In [2]:
a = tf.constant(10.)
b = tf.constant(20.)
c = tf.add(a, b)

# Tensor의 기본 메타 정보만 보여줌
print(c)

Tensor("Add:0", shape=(), dtype=float32)


![](data/add.png)

In [3]:
# 그래프를 실행할 세션 구성
sess = tf.Session()

# sess.run: 텐서 그래프 실행
print(sess.run([a, b, c]))

[10.0, 20.0, 30.0]


# tf.placeholder

In [4]:
X = tf.placeholder(tf.float32, [None, 2])
print(X)

Tensor("Placeholder:0", shape=(?, 2), dtype=float32)


$$
\text{x_data} = \left(\begin{array}{cc} 1\,\, 2 \\ 3\,\, 4\end{array}\right)
$$

In [5]:
# X 플레이스홀더에 대입하는 값
x_data = [[1, 2], [3, 4]]

In [6]:
# X값 print 하기
print(sess.run(X, feed_dict={X: x_data}))

[[1. 2.]
 [3. 4.]]


# tf.Variable

$$
\text{W} = \left(\begin{array}{cc} 1\,\, 1 \\ 2\,\, 2\end{array}\right)
$$

$$
\text{b} = \left(\begin{array}{cc} b_{11}\,\, b_{12} \\ b_{21}\,\, b_{22}\end{array}\right)
$$

$$
H = XW + b = \left(\begin{array}{cc} 1\,\, 2 \\ 3\,\, 4\end{array}\right)\left(\begin{array}{cc} 1\,\, 1 \\ 2\,\, 2\end{array}\right)+\left(\begin{array}{cc} b_{11}\,\, b_{12} \\ b_{21}\,\, b_{22}\end{array}\right)
$$

In [7]:
# tf.random_normal: 정규분포(평균 = 0, 표준편차 =1)

#초깃값을 고정해서 배정
W = tf.Variable([[1., 1.],[2., 2.]])

#초깃값을 정규분포에서 추출
b = tf.Variable(tf.random_normal([2, 2])) 

# 입력값과 변수들을 계산할 수식 작성
H = tf.matmul(X, W) + b

In [8]:
sess = tf.Session()

# Variable은 초기화를 해야함
sess.run(tf.global_variables_initializer())

print(sess.run(W))

print(sess.run(b))

[[1. 1.]
 [2. 2.]]
[[-0.74557287  1.8081607 ]
 [-0.9116307   0.35201246]]


In [9]:
print(sess.run(H, feed_dict={X: x_data}))

[[ 4.254427  6.808161]
 [10.088369 11.352013]]
